# src/main/resources/application-dev.yml (разработка)

spring:
#  datasource:
#    # 🟢 ИСПРАВЛЕНО: Теперь dev-режим смотрит на правильный выделенный порт платформы и общую базу
#    url: jdbc:postgresql://localhost:5433/logistics_platform_db?currentSchema=cargo_schema
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update # На деве разрешаем Hibernate обновлять схему на лету
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow          # 👈 GMT+3

  # ============================================================
  # 🔐 SPRING SECURITY
  # ============================================================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/logistics-platform}

logging:
  level:
    root: INFO                                        # Системные логи Спринга — только INFO
    com.innowise.logistics.cargoservice: DEBUG       # Весь твой сервис целиком переводим в DEBUG
    com.innowise.logistics.cargoservice.controller: DEBUG # 🎯 Жестко и принудительно включаем DEBUG для контроллеров
    org.springframework.web: DEBUG                   # Позволит увидеть сам факт прихода Multipart-запроса
